var f = {
	"unique": "6",
	"name": "SHO110P1",
	"number": "7",
	"fldcnt": "50",
	"buf_len": "662",
	"descr": "PURCHASE ORDER ENTRY (HEADER) - Add mode",
	"dataFields": [
		{
			"type": "field",
			"element": "text",
			"rownum": "2",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "1",
			"scrnord": "1",
			"name": "DATE",
			"title": "Title goes here",
			"length": "8",
			"value": " ",
			"column": "64",
			"fieldtype": "D",
			"bufstart": "1",
			"bufend": "8",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "2",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "45",
			"scrnord": "2",
			"name": "TIME1",
			"title": "Title goes here",
			"length": "5",
			"value": " ",
			"column": "74",
			"fieldtype": "D",
			"bufstart": "9",
			"bufend": "13",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "3",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "2",
			"scrnord": "3",
			"name": "COMPANYNAME",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "3",
			"fieldtype": "D",
			"bufstart": "14",
			"bufend": "43",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "3",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "44",
			"scrnord": "4",
			"name": "REVLEVEL",
			"title": "Title goes here",
			"length": "11",
			"value": " ",
			"column": "68",
			"fieldtype": "D",
			"bufstart": "44",
			"bufend": "54",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "5",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "3",
			"scrnord": "5",
			"name": "PONO",
			"title": "Title goes here",
			"length": "22",
			"value": " ",
			"column": "12",
			"fieldtype": "R",
			"bufstart": "55",
			"bufend": "76",
			"procspec": "\n    IF PONO MATCH d* THEN\n       JUSTIFY RIGHT; FILL LEADING \"0\"\n    ELSE\n       JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "5",
			"enh": "B",
			"datatype": "CHAR",
			"fieldnum": "4",
			"scrnord": "6",
			"name": "POSTATUS",
			"title": "Title goes here",
			"length": "20",
			"value": " ",
			"column": "36",
			"fieldtype": "D",
			"bufstart": "77",
			"bufend": "96",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "5",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "49",
			"scrnord": "7",
			"name": "COMPDT",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "57",
			"fieldtype": "D",
			"bufstart": "97",
			"bufend": "102",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "5",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "46",
			"scrnord": "8",
			"name": "D",
			"title": "Title goes here",
			"length": "1",
			"value": " ",
			"column": "78",
			"fieldtype": "D",
			"bufstart": "103",
			"bufend": "103",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "6",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "5",
			"scrnord": "9",
			"name": "CUSTNO",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "12",
			"fieldtype": "R",
			"bufstart": "104",
			"bufend": "109",
			"procspec": "\n    IF CUSTNO MATCH d* THEN\n       JUSTIFY RIGHT; FILL LEADING \"0\"\n    ELSE\n       JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "6",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "6",
			"scrnord": "10",
			"name": "CUSTNAME",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "20",
			"fieldtype": "D",
			"bufstart": "110",
			"bufend": "139",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "6",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "51",
			"scrnord": "11",
			"name": "MARKET",
			"title": "Title goes here",
			"length": "20",
			"value": " ",
			"column": "59",
			"fieldtype": "D",
			"bufstart": "140",
			"bufend": "159",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "7",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "7",
			"scrnord": "12",
			"name": "VENDOR",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "160",
			"bufend": "165",
			"procspec": "\n    IF MATCH d* THEN\n       JUSTIFY RIGHT; FILL LEADING \"0\"\n    ELSE\n       JUSTIFY LEFT;\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "7",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "8",
			"scrnord": "13",
			"name": "VENDNAME",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "20",
			"fieldtype": "O",
			"bufstart": "166",
			"bufend": "195",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "8",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "9",
			"scrnord": "14",
			"name": "BY",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "196",
			"bufend": "199",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "8",
			"enh": "U",
			"datatype": "DIG ",
			"fieldnum": "42",
			"scrnord": "15",
			"name": "F",
			"title": "Title goes here",
			"length": "1",
			"value": " ",
			"column": "30",
			"fieldtype": "O",
			"bufstart": "200",
			"bufend": "200",
			"procspec": "\n    FINISH\n    JUSTIFY RIGHT; FILL LEADING \"0\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "8",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "40",
			"scrnord": "16",
			"name": "CONTACT",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "32",
			"fieldtype": "D",
			"bufstart": "201",
			"bufend": "230",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "8",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "41",
			"scrnord": "17",
			"name": "PHNO",
			"title": "Title goes here",
			"length": "10",
			"value": " ",
			"column": "63",
			"fieldtype": "D",
			"bufstart": "231",
			"bufend": "240",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "10",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "10",
			"scrnord": "18",
			"name": "EXDATE",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "12",
			"fieldtype": "D",
			"bufstart": "241",
			"bufend": "246",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "10",
			"enh": "U",
			"datatype": "MDY ",
			"fieldnum": "11",
			"scrnord": "19",
			"name": "ORDATE",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "34",
			"fieldtype": "O",
			"bufstart": "247",
			"bufend": "252",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "10",
			"enh": "U",
			"datatype": "MDY ",
			"fieldnum": "12",
			"scrnord": "20",
			"name": "DEDATE",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "53",
			"fieldtype": "O",
			"bufstart": "253",
			"bufend": "258",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "10",
			"enh": "U",
			"datatype": "MDY ",
			"fieldnum": "13",
			"scrnord": "21",
			"name": "SHDATE",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "73",
			"fieldtype": "O",
			"bufstart": "259",
			"bufend": "264",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "11",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "14",
			"scrnord": "22",
			"name": "TIME",
			"title": "Title goes here",
			"length": "5",
			"value": " ",
			"column": "12",
			"fieldtype": "D",
			"bufstart": "265",
			"bufend": "269",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "11",
			"enh": "U",
			"datatype": "MDY ",
			"fieldnum": "39",
			"scrnord": "23",
			"name": "PRDATE",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "34",
			"fieldtype": "O",
			"bufstart": "270",
			"bufend": "275",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "11",
			"enh": "U",
			"datatype": "MDY ",
			"fieldnum": "50",
			"scrnord": "24",
			"name": "RVDATE",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "53",
			"fieldtype": "O",
			"bufstart": "276",
			"bufend": "281",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "11",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "48",
			"scrnord": "25",
			"name": "Y",
			"title": "Title goes here",
			"length": "1",
			"value": " ",
			"column": "73",
			"fieldtype": "R",
			"bufstart": "282",
			"bufend": "282",
			"procspec": "\n    IN \"Y\",\"N\" \"*** VALID OPTIONS ARE 'Y' OR 'N' ***\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "12",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "15",
			"scrnord": "26",
			"name": "REQNO",
			"title": "Title goes here",
			"length": "12",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "283",
			"bufend": "294",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "12",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "16",
			"scrnord": "27",
			"name": "PROJ",
			"title": "Title goes here",
			"length": "6",
			"value": " ",
			"column": "34",
			"fieldtype": "O",
			"bufstart": "295",
			"bufend": "300",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "13",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "43",
			"scrnord": "28",
			"name": "NOTE01",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "301",
			"bufend": "330",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "13",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "47",
			"scrnord": "29",
			"name": "N",
			"title": "Title goes here",
			"length": "1",
			"value": " ",
			"column": "57",
			"fieldtype": "O",
			"bufstart": "331",
			"bufend": "331",
			"procspec": "\n    IN \"Y\",\"N\"  \"*** VALID OPTIONS ARE 'Y' OR 'N' ***\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "14",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "18",
			"scrnord": "30",
			"name": "VENDEENAME",
			"title": "Title goes here",
			"length": "34",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "332",
			"bufend": "365",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "15",
			"enh": "U",
			"datatype": "DIG ",
			"fieldnum": "19",
			"scrnord": "31",
			"name": "A",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "366",
			"bufend": "369",
			"procspec": "\n    IN 1:9999   \"*** MUST BE GREATER THAN 0 ***\"\n    FINISH\n    JUSTIFY RIGHT; FILL LEADING \"0\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "15",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "20",
			"scrnord": "32",
			"name": "ADVISE1",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "17",
			"fieldtype": "D",
			"bufstart": "370",
			"bufend": "399",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "16",
			"enh": "U",
			"datatype": "DIG ",
			"fieldnum": "21",
			"scrnord": "33",
			"name": "B",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "400",
			"bufend": "403",
			"procspec": "\n    IN 1:9999   \"*** MUST BE GREATER THAN 0 ***\"\n    FINISH\n    JUSTIFY RIGHT; FILL LEADING \"0\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "16",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "22",
			"scrnord": "34",
			"name": "ADVISE2",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "17",
			"fieldtype": "D",
			"bufstart": "404",
			"bufend": "433",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "17",
			"enh": "U",
			"datatype": "DIG ",
			"fieldnum": "23",
			"scrnord": "35",
			"name": "C",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "12",
			"fieldtype": "O",
			"bufstart": "434",
			"bufend": "437",
			"procspec": "\n    IN 1:9999   \"*** MUST BE GREATER THAN 0 ***\"\n    FINISH\n    JUSTIFY RIGHT; FILL LEADING \"0\";\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "17",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "24",
			"scrnord": "36",
			"name": "ADVISE3",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "17",
			"fieldtype": "D",
			"bufstart": "438",
			"bufend": "467",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "17",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "25",
			"scrnord": "37",
			"name": "PDIS",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "74",
			"fieldtype": "R",
			"bufstart": "468",
			"bufend": "471",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "18",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "26",
			"scrnord": "38",
			"name": "DEST",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "16",
			"fieldtype": "R",
			"bufstart": "472",
			"bufend": "475",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "18",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "27",
			"scrnord": "39",
			"name": "DESTNAME",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "21",
			"fieldtype": "D",
			"bufstart": "476",
			"bufend": "505",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "18",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "28",
			"scrnord": "40",
			"name": "PDISNAME",
			"title": "Title goes here",
			"length": "20",
			"value": " ",
			"column": "58",
			"fieldtype": "D",
			"bufstart": "506",
			"bufend": "525",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "19",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "29",
			"scrnord": "41",
			"name": "FT",
			"title": "Title goes here",
			"length": "2",
			"value": " ",
			"column": "18",
			"fieldtype": "R",
			"bufstart": "526",
			"bufend": "527",
			"procspec": "\n    JUSTIFY LEFT\n    IN \"P\", \"C\"   \"*** MUST BE 'P' OR 'C' ***\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "19",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "30",
			"scrnord": "42",
			"name": "FTLIT",
			"title": "Title goes here",
			"length": "7",
			"value": " ",
			"column": "21",
			"fieldtype": "D",
			"bufstart": "528",
			"bufend": "534",
			"procspec": "\n    FINISH\n    IF FT EQ \"C\" THEN\n       SET TO \"COLLECT\"\n    ELSE\n       SET TO \"PREPAID\";\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "19",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "31",
			"scrnord": "43",
			"name": "EM",
			"title": "Title goes here",
			"length": "2",
			"value": " ",
			"column": "44",
			"fieldtype": "R",
			"bufstart": "535",
			"bufend": "536",
			"procspec": "\n    JUSTIFY LEFT\n    IN \"  \", \"AU\", \"A \", \"O \", \"OU\", \"MF\", \"PP\", \"MB\", \"HC\", \"WA\", \"AO\", \"IM\"\n    \"*** VALID CODES 'AU', 'A', 'AO', 'O', 'OU', 'MF', 'PP', 'MB', 'HC', 'WA', 'IM'\"\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "19",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "32",
			"scrnord": "44",
			"name": "EMLIT",
			"title": "Title goes here",
			"length": "10",
			"value": " ",
			"column": "47",
			"fieldtype": "D",
			"bufstart": "537",
			"bufend": "546",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "19",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "33",
			"scrnord": "45",
			"name": "PEXP",
			"title": "Title goes here",
			"length": "4",
			"value": " ",
			"column": "74",
			"fieldtype": "O",
			"bufstart": "547",
			"bufend": "550",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "20",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "34",
			"scrnord": "46",
			"name": "SHIP_TO1",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "13",
			"fieldtype": "O",
			"bufstart": "551",
			"bufend": "580",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "20",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "35",
			"scrnord": "47",
			"name": "PEXPNAME",
			"title": "Title goes here",
			"length": "20",
			"value": " ",
			"column": "58",
			"fieldtype": "D",
			"bufstart": "581",
			"bufend": "600",
			"procspec": " "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "21",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "36",
			"scrnord": "48",
			"name": "SHIP_TO2",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "13",
			"fieldtype": "O",
			"bufstart": "601",
			"bufend": "630",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "22",
			"enh": "U",
			"datatype": "CHAR",
			"fieldnum": "37",
			"scrnord": "49",
			"name": "SHIP_TO3",
			"title": "Title goes here",
			"length": "30",
			"value": " ",
			"column": "13",
			"fieldtype": "O",
			"bufstart": "631",
			"bufend": "660",
			"procspec": "\n    FINISH\n    JUSTIFY LEFT\n   "
		},
		{
			"type": "field",
			"element": "text",
			"rownum": "22",
			"enh": "NONE",
			"datatype": "CHAR",
			"fieldnum": "38",
			"scrnord": "50",
			"name": "MO",
			"title": "Title goes here",
			"length": "2",
			"value": " ",
			"column": "77",
			"fieldtype": "D",
			"bufstart": "661",
			"bufend": "662",
			"procspec": " "
		}
	],
	"textFields": [
		{
			"type": "static",
			"rownum": "2",
			"enh": "NONE-S",
			"staticnum": "0",
			"value": "SHO110P",
			"width": "7",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "2",
			"enh": "NONE-S",
			"staticnum": "1",
			"value": "PURCHASE ORDER HEADER",
			"width": "21",
			"column": "30",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "5",
			"enh": "NONE-S",
			"staticnum": "2",
			"value": "PO# :",
			"width": "6",
			"column": "6",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "5",
			"enh": "NONE-S",
			"staticnum": "3",
			"value": "Set Delete:",
			"width": "12",
			"column": "66",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "6",
			"enh": "NONE-S",
			"staticnum": "4",
			"value": "Cust No:",
			"width": "9",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "6",
			"enh": "NONE-S",
			"staticnum": "5",
			"value": "Market:",
			"width": "8",
			"column": "51",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "7",
			"enh": "NONE-S",
			"staticnum": "6",
			"value": "Vendor#:",
			"width": "9",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "8",
			"enh": "NONE-S",
			"staticnum": "7",
			"value": "Buyer",
			"width": "5",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "8",
			"enh": "NONE-S",
			"staticnum": "8",
			"value": ":",
			"width": "2",
			"column": "10",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "8",
			"enh": "NONE-S",
			"staticnum": "9",
			"value": "Contact#:",
			"width": "10",
			"column": "20",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "10",
			"enh": "NONE-S",
			"staticnum": "10",
			"value": "PO Date:",
			"width": "9",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "10",
			"enh": "NONE-S",
			"staticnum": "11",
			"value": "Order Date:",
			"width": "12",
			"column": "22",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "10",
			"enh": "NONE-S",
			"staticnum": "12",
			"value": "Issue Date:",
			"width": "12",
			"column": "41",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "10",
			"enh": "NONE-S",
			"staticnum": "13",
			"value": "Field Date:",
			"width": "12",
			"column": "61",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "11",
			"enh": "NONE-S",
			"staticnum": "14",
			"value": "Time:",
			"width": "6",
			"column": "6",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "11",
			"enh": "NONE-S",
			"staticnum": "15",
			"value": "Promise Dt:",
			"width": "12",
			"column": "22",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "11",
			"enh": "NONE-S",
			"staticnum": "16",
			"value": "Revised:",
			"width": "9",
			"column": "44",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "11",
			"enh": "NONE-S",
			"staticnum": "17",
			"value": "Direct Req:",
			"width": "12",
			"column": "61",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "12",
			"enh": "NONE-S",
			"staticnum": "18",
			"value": "Req no.:",
			"width": "9",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "12",
			"enh": "NONE-S",
			"staticnum": "19",
			"value": "Project:",
			"width": "9",
			"column": "25",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "13",
			"enh": "NONE-S",
			"staticnum": "20",
			"value": "Notes:",
			"width": "7",
			"column": "5",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "13",
			"enh": "NONE-S",
			"staticnum": "21",
			"value": "More Notes:",
			"width": "12",
			"column": "45",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "14",
			"enh": "NONE-S",
			"staticnum": "22",
			"value": "Vendee :",
			"width": "9",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "15",
			"enh": "NONE-S",
			"staticnum": "23",
			"value": "Advice :",
			"width": "9",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "16",
			"enh": "NONE-S",
			"staticnum": "24",
			"value": "Codes:",
			"width": "7",
			"column": "5",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "17",
			"enh": "NONE-S",
			"staticnum": "25",
			"value": ":",
			"width": "2",
			"column": "10",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "17",
			"enh": "NONE-S",
			"staticnum": "26",
			"value": "Port of Discharge:",
			"width": "19",
			"column": "55",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "18",
			"enh": "NONE-S",
			"staticnum": "27",
			"value": "Destination:",
			"width": "13",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "19",
			"enh": "NONE-S",
			"staticnum": "28",
			"value": "Freight Terms:",
			"width": "15",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "19",
			"enh": "NONE-S",
			"staticnum": "29",
			"value": "Export Method:",
			"width": "15",
			"column": "29",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "19",
			"enh": "NONE-S",
			"staticnum": "30",
			"value": "Port of Export:",
			"width": "16",
			"column": "58",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "20",
			"enh": "NONE-S",
			"staticnum": "31",
			"value": "Ship-To:",
			"width": "8",
			"column": "3",
			"align": "s-right"
		},
		{
			"type": "static",
			"rownum": "22",
			"enh": "NONE-S",
			"staticnum": "32",
			"value": "Menu Op",
			"width": "8",
			"column": "69",
			"align": "s-right"
		}
	],
	"Functionkeys": [
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "1",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f1  ",
			"value2": "  ADD                ",
			"column": "1",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "2",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f2  ",
			"value2": " CHANGE                ",
			"column": "10",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "3",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f3  ",
			"value2": " DELETE                ",
			"column": "19",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "4",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f4  ",
			"value2": "INQUIRE                ",
			"column": "28",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "5",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f5  ",
			"value2": "             ",
			"column": "45",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "6",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f6  ",
			"value2": "ITM ENTR                ",
			"column": "54",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "7",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f7  ",
			"value2": "MENU OP                ",
			"column": "63",
			"fieldtype": "FK",
			"procspec": ""
		},
		{
			"type": "fkey",
			"rownum": "25",
			"keynum": "8",
			"scrnord": "",
			"name": "FKEY",
			"length": "16",
			"value1": "   f8  ",
			"value2": "  EXIT                ",
			"column": "72",
			"fieldtype": "FK",
			"procspec": ""
		}
	],
	"fieldSets": [
		{
			"type": "fieldset",
			"rownum": "1",
			"class": "fs7",
			"height": "12",
			"width": "80",
			"column": "1",
			"title": ""
		},
		{
			"type": "fieldset",
			"rownum": "4",
			"class": "fs7",
			"height": "72",
			"width": "80",
			"column": "1",
			"title": ""
		}
	]
}
